### ISSUE TITLE
virt-deploy should require new enough libguestfs-tools-c version

### ISSUE THREAD

**Issue by mvollmer** [simon3z/virt-deploy#11]
I got this:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 105, in instance_create
    base = _create_base(template, kwargs['arch'], repository)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 264, in _create_base
    '--root-password', 'locked:disabled'))
  File "/usr/lib/python2.7/site-packages/virtdeploy/utils.py", line 31, in execute
    p = subprocess.Popen(args, stdout=stdout, stderr=stderr, cwd=cwd)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I think it tries to run `virt-builder` here.

It went away after updating libguestfs-tools-c from 1.22.6 to 1.28.1, so I guess virt-builder wasn't in my old version.

**Comment by mvollmer** [comment]
Thanks!
