### ISSUE TITLE
virt-deploy should depend on python-lxml

### ISSUE THREAD

**Issue by mvollmer** [simon3z/virt-deploy#12]
Otherwise:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/virtdeploy/__init__.py", line 38, in get_driver
    return get_driver_class(name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/virtdeploy/__init__.py", line 33, in get_driver_class
    module = __import__(DRIVERS[name][0], globals(), locals(), name, 1)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 30, in <module>
    from lxml import etree
ImportError: No module named lxml
```

**Comment by simon3z** [comment]
@mvollmer are you referring to setup.py? currently the spec file should be ok (requires libxml2-python)

**Comment by mvollmer** [comment]
No, the traceback happens when running virt-deploy itself, on Fedora, when python-lxml is not installed.  Sorry for not being clear about this.

**Comment by simon3z** [comment]
@mvollmer if you're installing the virt-deploy rpm then python-lxml must be there

https://copr.fedoraproject.org/coprs/fsimonce/virt-deploy/
