### ISSUE TITLE
fedora-23 template: virt-resize: error: unknown/unavailable method for expanding the xfs  filesystem on /dev/sda3

### ISSUE THREAD

**Issue by cben** [simon3z/virt-deploy#26]
No idea if this is virt-deploy's fault, but creating a `fedora-23` fails reproducibly:

```
$ sudo virt-deploy create miq1 fedora-23
[   2.0] Downloading: http://libguestfs.org/download/builder/fedora-23.xz
[   3.3] Planning how to build this image
[   3.3] Uncompressing
[  33.5] Resizing (using virt-resize) to expand the disk to 20.0G
virt-resize: error: unknown/unavailable method for expanding the xfs 
filesystem on /dev/sda3

If reporting bugs, run virt-resize with debugging enabled and include the 
complete output:

  virt-resize -v -x [...]
Traceback (most recent call last):
  File "/bin/virt-deploy", line 9, in <module>
    load_entry_point('virt-deploy==0.1.7', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 154, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 149, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 43, in instance_create
    instance = driver.instance_create(args.id, args.template)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 106, in instance_create
    base = _create_base(template, kwargs['arch'], repository)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 265, in _create_base
    '--root-password', 'locked:disabled'))
  File "/usr/lib/python2.7/site-packages/virtdeploy/utils.py", line 40, in execute
    raise subprocess.CalledProcessError(p.returncode, args)
subprocess.CalledProcessError: Command '('virt-builder', 'fedora-23', '-o', '/var/lib/libvirt/images/_fedora-23-x86_64.qcow2', '--size', '20G', '--format', 'qcow2', '--arch', 'x86_64', '--root-password', 'locked:disabled')' returned non-zero exit status 1
```

Works fine with centos-7.1 template.

I'm running this on a Fedora 23 x86_64 desktop, with virt-deploy from rpm copr.

**Comment by simon3z** [comment]
Thanks @cben 

@rwmjones any idea why `virt-resize` may be failing for `xfs` file-systems?
(At least that's what I get from the error)

**Comment by lyarwood** [comment]
@cben @simon3z Just hit this issue myself with `virt-builder`, you need to ensure `libguestfs-xfs` is installed :

http://libguestfs.org/virt-resize.1.html#unknown-unavailable-method-for-expanding-the-type-filesystem-on-device-lv

**Comment by simon3z** [comment]
Thanks @lyarwood 

Can anyone ( @lyarwood @cben ) send a patch to add the dependency here? Thanks!
