### ISSUE TITLE
error when deleting created instance (more snapshots)

### ISSUE THREAD

**Issue by jscotka** [simon3z/virt-deploy#6]
Hi,
unable to delete domain althought it was created by virt deploy. 
It seems that it is that I'm using avocado testing framework with virtual plugin, what have parameter --vm-cleanup -> restore machine after test (probably creates snapshots) http://avocado-framework.readthedocs.org/en/latest/VirtualMachinePlugin.html#vm-plugin-basics

so that next  command fais (I think it could be solved in virt-deploy, to deal with created snapshots and delete also them): 

$ sudo virt-deploy delete $NAME
Traceback (most recent call last):
  File "/bin/virt-deploy", line 9, in <module>
    load_entry_point('virtdeploy==0.1.5', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 135, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 130, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 58, in instance_delete
    return driver.instance_delete(args.name)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 262, in instance_delete
    dom.undefine()
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 2577, in undefine
    if ret == -1: raise libvirtError ('virDomainUndefine() failed', dom=self)
libvirt.libvirtError: Requested operation is not valid: cannot delete inactive domain with 2 snapshots

**Comment by simon3z** [comment]
Ok thanks, I'll fix this now.
