### ISSUE TITLE
error when default storage pool is missing

### ISSUE THREAD

**Issue by screeley44** [simon3z/virt-deploy#8]
1.  my work laptop is rhel 6.5
2.  I have created f21 VM (named miqbuild.rhs)
3.  from the f21 VM I have successfully performed these commands:
         dnf copr enable fsimonce/virt-deploy
         dnf install virt-deploy virt-address
4.  Now when I try to create the instance, I get this:

[root@miqbuild ~]# virt-deploy create test01 fedora-21
Traceback (most recent call last):
  File "/usr/bin/virt-deploy", line 9, in <module>
    load_entry_point('virt-deploy==0.1.6', 'console_scripts', 'virt-deploy')()
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 143, in main
    return parse_command_line(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 138, in parse_command_line
    return COMMAND_TABLE[args.command](args)
  File "/usr/lib/python2.7/site-packages/virtdeploy/cli.py", line 41, in instance_create
    instance = driver.instance_create(args.id, args.template)
  File "/usr/lib/python2.7/site-packages/virtdeploy/drivers/libvirt.py", line 96, in instance_create
    pool = conn.storagePoolLookupByName(kwargs['pool'])
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4305, in storagePoolLookupByName
    if ret is None:raise libvirtError('virStoragePoolLookupByName() failed', conn=self)
libvirt.libvirtError: Storage pool not found: no storage pool with matching name 'default'

Any idea what I'm missing at this point, or maybe my approach is completely wrong?

**Comment by simon3z** [comment]
@screeley44 what version are you using? (virt-deploy --version)

Latest version on copr is 0.1.6.

Can you check that you have the default pool defined in libvirt:

```
# virsh pool-list
 Name                 State      Autostart 
-------------------------------------------
 default              active     yes     
```

Thanks

**Comment by simon3z** [comment]
You can try to define the pool with:

```
# virsh pool-define /dev/stdin <<EOF
<pool type='dir'>
  <name>default</name>
  <target>
    <path>/var/lib/libvirt/images</path>
  </target>
</pool>
EOF

virsh pool-start default
virsh pool-autostart default
```

**Comment by screeley44** [comment]
that worked!! Thanks!!

## Name                 State      Autostart 

 default              active     yes

**Comment by simon3z** [comment]
Marking this as enhancement/help-wanted because adding the default storage pool when missing will improve user experience.

**Comment by jscotka** [comment]
Hi,
I've met similar issue. I have minimal installation and I've installed virt-deploy and it seems that "default" pool is not defined. 
It is caused also by missing dependency, what is not directly needed but this dependency create this pool.
it is package "virt-manager"
after installation of that package and reboot machine, pool is aviable.

So I'm not sure what is better solution, install dependendend virt-manager or create default pool + default network in own setup as workaround.
From this point of view I cannot decide  what is better.
it is connected with another issue:
https://github.com/simon3z/virt-deploy/issues/10

So my point of view is, that it would be nice, to not use default pool and default network but be able to config own pool for disc and net.
     Regards
     Honza

**Comment by jscotka** [comment]
My mentioned solution should also solve another issue:
I'm running virt-deploy under normal user ( not root) and I've added policy to 
/etc/polkit-1/localauthority/50-local.d/50-org.example-libvirt-remote-access.pkla
to allow some group work with virsh qemu:///system
All virsh qemu:///system comands works then well, but qemu-img command does not have access to /var/lib/libvirt/images (default pool location), so in case virt-deploy under normal user create this pool in some other dir where user/group has access it will be better. (/var/lib/libvirt/images/_fedora-21-x86_64.qcow2: qemu-img exited with error status 1.)

**Comment by jscotka** [comment]
Hi,
otherwise I found, that this default pool is created after command virt-manager is called (probably virt-manager do some init of "default" pool)
installation of virt-manager is not enouht
    Honza

**Comment by rrasouli** [comment]
error: Failed to define pool default
error: operation failed: Storage source conflict with pool: 'images'
SOLVED:
 virsh pool-list

##  Name                 State      Autostart 

 images               active     yes       

$ virsh pool-destroy images
Pool images destroyed

$ virsh pool-undefine images
Pool images has been undefined

Then restart the deployment

**Comment by huataihuang** [comment]
a reference to [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) README

storage_pool_name - Libvirt storage pool name, where box image and instance snapshots will be stored.

## My Solution

> Example: install [boxe  centos/7](https://atlas.hashicorp.com/centos/boxes/7)

* init Vagrant

```
vagrant init centos/7
```

* edit `Vagrantfile` config, in `provider` secition add config like follow:

```
Vagrant.configure("2") do |config|
  ...
  config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name = "images"
  end
  ...
end
```

* then, start install

```
vagrant up --provider libvirt
```

* (Option) if you like, you can add follow environment config to /etc/profile to make `libvirt` as default provider, then you not need `--provider libvirt` as vagrant parameter.

```
export VAGRANT_DEFAULT_PROVIDER=libvirt
```

**Comment by busti** [comment]
I had to define the pool using virtmanager instead of using `virsh` to get it to work.
